# Generated by Django 5.1.7 on 2025-04-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vac_management', '0004_alter_baseuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_superuser',
        ),
    ]
