# Generated by Django 5.1.7 on 2025-04-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vac_management', '0006_baseuser_is_superuser'),
    ]

    operations = [
    ]
