# Generated by Django 5.1.7 on 2025-04-09 15:50

from django.db import migrations

# Custom function to preserve gender values while fixing the field type
def fix_gender_values(apps, schema_editor):
    # Get the historical models
    BaseUser = apps.get_model('vac_management', 'BaseUser')
    # Update the database directly to ensure gender values are correct
    db_alias = schema_editor.connection.alias
    # This SQL will be executed by Django's ORM
    BaseUser.objects.using(db_alias).filter(gender='male').update(gender='male')
    BaseUser.objects.using(db_alias).filter(gender='female').update(gender='female')

class Migration(migrations.Migration):

    dependencies = [
        ('vac_management', '0007_fix_gender_field'),
    ]

    operations = [
        # Run custom function to fix gender values
        migrations.RunPython(fix_gender_values, reverse_code=migrations.RunPython.noop),
    ]
