# Generated by Django 5.1.7 on 2025-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_management', '0011_alter_appointment_staff_alter_baseuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
