# Generated by Django 5.1.7 on 2025-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_management', '0012_campaign_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
