# Generated by Django 5.1.7 on 2025-05-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_management', '0014_alter_campaign_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
