# Generated by Django 5.1.7 on 2025-05-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_management', '0015_alter_campaign_campaign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
