install_all:
	python -m pip install -r requirements.txt

runserver:
	python manage.py runserver

migrate:
	python manage.py migrate

makemigrations:
	python manage.py makemigrations vac_management

superuser:
	python manage.py createsuperuser
