install_all:
	pip install -r requirements.txt

runserver:
	manage.py runserver

migrate:
	python3 manage.py migrate

makemigrations:
	python3 manage.py makemigrations vac_management

superuser:
	python3 manage.py createsuperuser
